### PR TITLE
Propagate http.status_code as tagged metric

### PR DESCRIPTION
**Pull request by yarosman**
This PR allows you to configure using `http.status_code` as a metric tag or not

@ivantopo please review it

### CODE REVIEW

**Comment by dpsoft** [comment]
@yarosman LGTM. @ivantopo WDYT?

**Comment by ivantopo** [comment]
Hey @yarosman! The PR itself looks fine, just there is a small issue on the implementation.. we introduced a HTTP Server instrumentation component in core, you can see the code [here](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/instrumentation/HttpServer.scala) and that component already knows how to handle a bunch of stuff like, for example, adding the `http.status_code` tag based on configuration, take a look at [this settings](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/resources/reference.conf#L315-L342).

When I mentioned handling the tag as a separate PR I had in mind that we would upgrade the Play instrumentation to use this new component and then we get the tag management for free, sorry I didn't share this information at the moment :(.. would you consider reworking this PR to use the `HttpServer` instrumentation instead of just introducing this particular tag?

**Comment by yarosman** [comment]
Hello, @ivantopo ! I will look to Http server instrumentation with it configuration and try to update my PR

**Comment by yarosman** [comment]
@ivantopo in which version of kamon-core i can find this new feature ?

**Comment by pocman** [comment]
Hi all, this feature is really promising and a must have (from my point of view).
@yarosman it looks like the http server instrumentation is only on master and not yet released.
@ivantopo would you consider bumping to v1.1.6 or v1.2.0 ?

**Comment by Tenchi2xh** [comment]
Any news on this? Right now I see a status code in the akka-http generated metrics but on the play counterparts, would be greatly appreciated

**Comment by ivantopo** [comment]
Hey @yarosman, I'm closing this PR because this functionality was already introduced using the HTTP Server instrumentation mentioned above on Kamon 2.0. Thanks!

**Pull request closed without merging**
