### PR TITLE
Added monitoring for StandaloneWSClient

### PR DESCRIPTION
**Pull request by yarosman**
- added monitroring for StandaloneWSClient (play-2.6)
- made response status as tagged metric

### CODE REVIEW

**Comment by ivantopo** [comment]
Hey @yarosman, I just took a look at this (sorry for the delayed response :'() and noticed a couple things:

  1. It seems like there are two Play WS libraries: `play-ws` and `play-ws-standalone` and the instrumentation you are including here is changing the first to the second instead of adding some new pointcuts/instrumentation for the new library.. as is, it seems like this would stop working for some play apps and start working for some people using `play-ws-standalone`.. am I missing something here?
  2. We developed an HTTP server instrumentation thingy as part of core which allows you to configure a few details like whether to use `http.status_code` as a metric tag or not instead of adding it by default as you did on this PR, what do you think about keeping this PR just about instrumenting `play-ws-standalone` and let's handle the tag thing separately?

**Comment by yarosman** [comment]
Hey, @ivantopo 
1. Yes, you missed something. Under the hood **ws** uses **ws-standalone** https://github.com/playframework/playframework/blob/c9f3d7493bee45cc200f71422b390fbbb3e922f3/framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala#L16 
so instrumentation will work as previously for WsClient and will work with using StandaloneWSClient directly 
2. Do you suggest to move metric tag to separate pull request and add configuration for such cases ?

**Comment by ivantopo** [comment]
Thanks for the pointer in play-ws vs play-ws-standalone :smiley: 

Also, I see you already took care of the tag so we are good there! The only weird thing is the current failure on the travis build.. there is something about this:

```
java.lang.RuntimeException: akka.UnsupportedAkkaVersion: Current version of Akka is [2.5.17], but akka-http requires version [2.5.19]
```

Any ideas on that one?

**Comment by yarosman** [comment]
```scala
java.lang.RuntimeException: akka.UnsupportedAkkaVersion: Current version of Akka is [2.5.17], but akka-http requires version [2.5.19]
```

Fixed

**Pull request merged**
